spring:
  datasource:
    url: jdbc:h2:C:/H2/data/vgdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none